config/routes.rb
Pushcart::Application.routes.draw do

  devise_for :coaches
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  ### API ###

    scope 'api' do
      scope 'v1' do
        use_doorkeeper
      end

      api_version(module: 'api/v1', path: {value: 'v1'}, defaults: {format: 'json'}) do
        resources :users, only: [:show, :index] do
          resources :purchases, only: [:show, :index] do
            resources :itemizables, path: 'items', only: [:show, :index, :update]
          end
          resources :itemizables, path: 'items', only: [:show, :update]
          resources :messages
        end
        resources :swap_categories, only: :index
        resources :swaps, only: [:index, :create]
        resources :memberships, only: [] do
          post :invite, on: :collection
        end
      end
    end

  ######

  ### User Site ###
    resources :users, only: [:edit, :update]
    resources :items, only: [] do
      get :swap_feedback,  on: :member
    end
    resources :memberships, only: [:new, :create]
    devise_for :users, controllers: {
                                      registrations: 'user_registrations',
                                      confirmations: 'user_confirmations',
                                      omniauth_callbacks: 'users/omniauth_callbacks'
                                    }

    get 'account_confirmation',      to: 'users#account_confirmation'
    get 'my_account',                to: 'users#my_account'
    get 'thank_you_for_registering', to: 'users#thank_you_for_registering'
    get 'login_token_expired',       to: 'users#login_token_expired'
    post 'new_authentication_token', to: 'users#new_authentication_token'
    get 'edit_household',            to: 'users#edit_household'
    delete 'sign_out',               to: 'users#log_out',  as: 'sign_out_user'
  ######

  ### Email ###
    mount_griddler

    # # Temporary route just used to validate Mandrill. See: https://github.com/thoughtbot/griddler#using-griddler-with-mandrill
    # get "/email_processor", to: proc { [200, {}, ["OK"]] }, as: "mandrill_head_test_request"

  root to: 'application#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_token_authenticatable

  devise :registerable, :timeoutable, :trackable, :omniauthable, :omniauth_providers => [:google_oauth2]

  has_many :purchases
  has_many :itemizables, through: :purchases
  has_many :items, through: :purchases
  has_many :swaps, through: :itemizables
  has_many :household_members, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :memberships
  has_many :coaches, through: :memberships

  belongs_to :mission

  after_initialize :set_endpoint_email
  after_create     :scrape_gmail,                   if: Proc.new { |u| u.identity_provider == 'gmail' }
  after_save       :send_onboarding_emails,         if: Proc.new { |u| u.confirmed_at_changed? && u.confirmed_at_was.nil? }
  after_save       :send_pushcart_endpoint_mailer,  if: Proc.new { |u| u.endpoint_email_changed? && !u.confirmed_at_was.nil? && u.identity_provider.nil? }

  validates_presence_of   :email, :endpoint_email
  validates_uniqueness_of :email, :endpoint_email

  accepts_nested_attributes_for :household_members


  def endpoint_email_with_uri
    "#{endpoint_email}@#{EMAIL_URI}"
  end

  def household_size
    household_members.count
  end

  def login_token_expired?
    login_token_expires_at.blank? || Time.now > login_token_expires_at
  end

  def return_or_set_login_token
    if authentication_token.nil? || authentication_token_expires_at.blank? || Time.now > authentication_token_expires_at
      self.authentication_token = nil
      save
      authentication_token
    else
      authentication_token
    end
  end

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(email: data['email']).first

    unless user
      user = User.create(
                          name: data['name'],
                          email: data['email'],
                          identity_provider: 'gmail',
                          inbox_api_token: access_token.credentials
                        )
    end

    user
  end

  def send_onboarding_emails
    UserMailer.delay.getting_started(self.id) if (household_size == 0 || mission_id.nil?) && identity_provider.nil?
    send_pushcart_endpoint_mailer
  end

  def send_pushcart_endpoint_mailer
    UserMailer.delay.new_pushcart_endpoint_email(self.id)
  end

  def generate_endpoint_email_recommendation
    email_root = /^[^\@]*/.match(email)[0].downcase
    recommendation = email_root.dup
    trailer = 1

    until User.find_by_endpoint_email(recommendation).nil?
      recommendation = "#{email_root}-#{trailer}"
      trailer += 1
    end

    self.endpoint_email = recommendation
  end

private

  def scrape_gmail
    GmailProcessor.delay.process(self.id)
  end

  def set_endpoint_email
    generate_endpoint_email_recommendation if endpoint_email.blank?
  end

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseCoachController

  before_action :set_user, only: :show

  def index
    @users = @coach.members
  end

  def show
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.find_for_google_oauth2(request.env['omniauth.auth'], current_user)

    if @user.persisted?
      flash[:notice] = 'You have successfully registered with Gmail!'
      sign_in_and_redirect @user, :event => :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth']
      flash[:notice] = 'There was an error authenticating your Gmail account.'
      redirect_to root_path
    end
  end

  def after_omniauth_failure_path_for(resource)
    flash[:notice] = 'There was an error authenticating your Gmail account.'
    return root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  acts_as_token_authentication_handler_for User, fallback_to_devise: false

  before_action :set_user_or_redirect, except: [ :thank_you_for_registering,
                                                 :login_token_expired,
                                                 :new_login_token ]

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash[:notice] = 'Your settings were successfully updated.'
      redirect_to action: 'my_account'
    else
      flash[:error] = @user.errors
      redirect_to :back
    end
  end

  def thank_you_for_registering
  end

  def account_confirmation
  end

  def my_account
  end

  def change_settings
  end

  def log_out
    sign_out @user
    flash[:notice] = 'You have successfully logged out.'
    redirect_to :root
  end

  def login_token_expired
    @ref = params[:ref]
  end

  def new_authentication_token
    @return_path = params[:return_path]
    @user = User.find_by_email(params[:email])
    UserMailer.delay.resend_login_url(@user.id, @return_path)
    flash[:notice] = "Thank you! Check your e-mail for your new login URL."
    redirect_to :back
  end

  def edit_household
    @user.household_members.build
  end

protected

  def user_params
    params.require(:user).permit( 
                                  :endpoint_email,
                                  :mission_id,
                                  household_members_attributes: [
                                                                  :id,
                                                                  :age,
                                                                  :gender,
                                                                  :_destroy
                                                                ]
                                )
  end

end

app/views/users/_form.haml
= simple_form_for @user do |f|
  .row
    .col-md-offset-2.col-md-1
      Endpoint email
    .col-md-4
      = f.input :endpoint_email, label: false
    .col-md-3
      = "@#{EMAIL_URI}"
  .row
    .col-md-offset-1.col-md-8
      %p This e-mail address is where all your grocery receipts should be sent. Once you change it, we recommend that you update it in any auto-mailers or grocery accounts immediately, as we will no longer forward e-mails sent to the old endpoint address.
  .row
    .col-md-offset-2
      = f.button :submit, 'Update my settings', class: 'button'

app/views/users/_getting_started.haml
.container
  .row
    .col-md-offset-1.col-md-10
      - if confirmation
        %h1 Congratulations, your account is confirmed!
      - else
        %h1 Your Pushcart account
  .row
    .col-md-offset-1.col-md-8
      %h2 Your Pushcart forwarding address
  .row
    .col-md-offset-2.col-md-8
      %p Your Pushcart forwarding e-mail address is a filter for grabbing your grocery receipt data. Here's yours:
      %p
        %b
          = @user.endpoint_email_with_uri
      %p
        Want to change your Pushcart forwarding e-mail address to something else?
        - if mailer
          = link_to 'Click here.', url_with_login_token(@user, edit_user_url(@user))
        - else
          = link_to 'Click here.', edit_user_path(@user)
      %p Simply send receipts to this address and we'll make sure that we collect all the important data you need to know about your grocery shopping for you.
  .row
    .col-md-offset-1.col-md-10
      %h2 Your household information
  .row
    .col-md-offset-2.col-md-8
      %h3 Household Mission
      - if @user.mission_id.nil?
        %p
          = "You have not yet set a mission for your household."
          = link_to 'Please do so here.', url_with_login_token(@user, edit_household_url)
      - else
        %p
          %b
            = @user.mission.name
      %h3 Household Demographics
      - if @user.household_members.empty?
        %p
          = "You have not added any members to your household yet."
          = link_to 'Please do so here.', url_with_login_token(@user, edit_household_url)
      - else
        - @user.household_members.each_with_index do |hm, index|
          %p.col-md-12
            %b
              = "##{index+1} #{hm.gender}, #{hm.age} years old"
        = "Need to change your mission or demographic information?"
        = link_to 'You can do so here.', url_with_login_token(@user, edit_household_url)
  - if confirmation
    .col-md-offset-1.col-md-10
      %h2 One last thing to do
      %p To get started collecting your grocery data, all you need to do now is one of the following:
      %ol
        %li
          %p Set up an auto-forwarder to send all grocery receipt e-mails to your endpoint e-mail above. (If you like to micromanage your technology, you can also just manually forward e-mail your receipts.)
        %li
          %p Simply change your contact e-mail address on the grocery site to the endpoint e-mail. (Don't worry -- we will forward all e-mails from them on to you and won't store anything except for data about your purchases.)
    .col-md-offset-1.col-md-10
      %h2 Keep it for your records
      %p Not sure you'll remember this information, or how to navigate back to this page? Never fear: we've already sent you an e-mail with all the information on this page!

app/views/users/_new_login_token_form.haml
= form_tag new_login_token_path do
  .container
    .row
      .col-md-offset-2.col-md-8
        = text_field_tag "email", nil, placeholder: "your email address"
        = hidden_field_tag 'return_path', defined?(return_path) ? return_path : ''

    .row
      .col-md-offset-2
        = submit_tag "Submit", class: "button"

app/views/users/account_confirmation.html.haml
.container 
  .row
    .col-md-offset-2.col-md-8
      %h1 Your e-mail is confirmed!
  .row
    .col-md-offset-2.col-md-8
      %h3 Look for further instructions in your inbox on how to proceed with setting up Pushcart.

app/views/users/edit.html.haml
.row
  .col-md-offset-1
    %h1 Your settings

.row
  = render 'form'

app/views/users/edit_household.html.haml
.container
  .row
    .col-md-offset-3.col-md-8
      %h1 Your Household
  .row
    .col-md-9.col-md-offset-1
      %h3 Set your household mission
      %p Please tell us about a healthy change you’d like to make to your grocery shopping.

  = simple_nested_form_for @user do |f|
  
    .col-md-9.col-md-offset-1
      = f.input :mission_id, collection: Mission.all, label: false
    .row
      .col-md-9.col-md-offset-1
        %h3 Who are you shopping for?
        %p Having information on the number of people you shop for and their age helps us tailor our recommendations better. (Please include yourself.)
    #edit-form
      = f.fields_for :household_members do |hm_form|
        .row
          .col-md-1.col-md-offset-1
            %h5= 'Person'
          .col-md-3
            = hm_form.input :gender, collection: ['Male', 'Female', 'N/A'], label: false, prompt: 'Gender'
          .col-md-3
            = hm_form.input :age, collection: HouseholdMember.age_collection, label: false, prompt: 'Age'
          .col-md-2
            = hm_form.link_to_remove 'Remove', class: 'button person-button remove_nested_fields'
    .row
      .col-md-3.col-md-offset-1
        = f.link_to_add "Add person to household", :household_members, class: 'btn btn-primary', data: { target: "#edit-form" }
    .row
      .col-md-3.col-md-offset-5
        = f.button :submit, 'Submit', class: 'btn btn-primary'

app/views/users/login_token_expired.html.haml
.container
  .row
    .col-md-offset-1.col-md-10
      %h1 Link Expired

      %p It appears that the link you are trying to access is expired. We expire all links sent to you via e-mail after 8 hours, for your security.

      %p Please enter your e-mail below and we'll send you a new link that you can use.

      = render 'new_login_token_form', return_path: @ref

app/views/users/my_account.html.haml
= render 'getting_started', mailer: false, confirmation: false

app/views/users/thank_you_for_registering.html.haml
.container
  .row
    .col-md-offset-1.col-md-11
      %h1 Thank you for registering
      
      %p You're almost done! Just check your inbox for a confirmation e-mail and click on the link to complete the registration process.
      
      %p 
        Never got your confirmation e-mail? 
        = link_to "Click here.", new_confirmation_path(:user)
      