config/routes.rb
Pushcart::Application.routes.draw do

  devise_for :coaches
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  ### API ###

    scope 'api' do
      scope 'v1' do
        use_doorkeeper
      end

      api_version(module: 'api/v1', path: {value: 'v1'}, defaults: {format: 'json'}) do
        resources :users, only: [:show, :index] do
          resources :purchases, only: [:show, :index] do
            resources :itemizables, path: 'items', only: [:show, :index, :update]
          end
          resources :itemizables, path: 'items', only: [:show, :update]
          resources :messages
        end
        resources :swap_categories, only: :index
        resources :swaps, only: [:index, :create]
        resources :memberships, only: [] do
          post :invite, on: :collection
        end
      end
    end

  ######

  ### User Site ###
    resources :users, only: [:edit, :update]
    resources :items, only: [] do
      get :swap_feedback,  on: :member
    end
    resources :memberships, only: [:new, :create]
    devise_for :users, controllers: {
                                      registrations: 'user_registrations',
                                      confirmations: 'user_confirmations',
                                      omniauth_callbacks: 'users/omniauth_callbacks'
                                    }

    get 'account_confirmation',      to: 'users#account_confirmation'
    get 'my_account',                to: 'users#my_account'
    get 'thank_you_for_registering', to: 'users#thank_you_for_registering'
    get 'login_token_expired',       to: 'users#login_token_expired'
    post 'new_authentication_token', to: 'users#new_authentication_token'
    get 'edit_household',            to: 'users#edit_household'
    delete 'sign_out',               to: 'users#log_out',  as: 'sign_out_user'
  ######

  ### Email ###
    mount_griddler

    # # Temporary route just used to validate Mandrill. See: https://github.com/thoughtbot/griddler#using-griddler-with-mandrill
    # get "/email_processor", to: proc { [200, {}, ["OK"]] }, as: "mandrill_head_test_request"

  root to: 'application#index'
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{charset: 'utf-8'}
    %meta{content: "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}
    %meta{content: "yes", name: "apple-mobile-web-app-capable"}/
    %meta{content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", name: "viewport"}/
    %meta{content: "black", name: "apple-mobile-web-app-status-bar-style"}/
    %link{href: "http://fonts.googleapis.com/css?family=Patua+One", rel: "stylesheet", type: "text/css"}/
    %title= content_for?(:title) ? "#{SITE_NAME} | #{yield(:title)}" : "#{SITE_NAME}"
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags

    <!--[if IE]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    - if Rails.env.production?
      :javascript
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-56134966-1', 'gopushcart.com');
        ga('require', 'displayfeatures');
        ga('send', 'pageview');
      :javascript
        var WRInitTime=(new Date()).getTime();

  %body
    .row
      - if flash[:error]
        .alert-box{"data-alert" => ""}
          - flash[:error].each do |message|
            %li= message
          %a.close{:href => "#"} &times;
      - if flash[:notice]
        .alert-box.success{"data-alert" => ""}
          = flash[:notice]
          %a.close{:href => "#"} &times;

    = yield
    
    .container 
      .row
        .footer
        - if current_user && !current_page?('/')
          .user-info
            You are signed in as #{current_user.email}.
            = link_to 'Click here to sign out.', sign_out_user_path, method: :delete

    = javascript_include_tag 'application'
    - if Rails.env.production?
      :javascript
        document.write(unescape("%3Cscript%20src='"+
        (document.location.protocol=='https:'?
        "https://cdnssl.clicktale.net/www07/ptc/dc5a4952-28f7-463b-9987-fb5287523b31.js":
        "http://cdn.clicktale.net/www07/ptc/dc5a4952-28f7-463b-9987-fb5287523b31.js")+"'%20type='text/javascript'%3E%3C/script%3E"));